// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Service.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class BlogsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Blog.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Blogs", "\tTo verify a user can request his read blogs correctly", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Blogs")))
            {
                Service.Tests.Features.BlogsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table1.AddRow(new string[] {
                        "Thomas"});
            table1.AddRow(new string[] {
                        "Wiljag"});
#line 5
 testRunner.Given("The following user created events have been sent", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Writer"});
            table2.AddRow(new string[] {
                        "Dit is mijn eerste blog",
                        "Thomas"});
            table2.AddRow(new string[] {
                        "Deze blog heeft informatie over Test Automation",
                        "Thomas"});
            table2.AddRow(new string[] {
                        "De blog over de ISKS 2016",
                        "Wiljag"});
#line 9
 testRunner.And("The following blog created events have been sent", ((string)(null)), table2, "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Request the read articles for a user")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blogs")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("blog")]
        public virtual void RequestTheReadArticlesForAUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Request the read articles for a user", new string[] {
                        "blog"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reader",
                        "Blog Name"});
            table3.AddRow(new string[] {
                        "Wiljag",
                        "Dit is mijn eerste blog"});
            table3.AddRow(new string[] {
                        "Wiljag",
                        "Deze blog heeft informatie over Test Automation"});
#line 17
 testRunner.Given("The following blog read events are send", ((string)(null)), table3, "Given ");
#line 21
 testRunner.When("\'Wiljag\' requests his reads", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table4.AddRow(new string[] {
                        "Dit is mijn eerste blog"});
            table4.AddRow(new string[] {
                        "Deze blog heeft informatie over Test Automation"});
#line 22
 testRunner.Then("The following blogs are returned", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Reading a blog will show up in the read blogs list")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blogs")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("blog")]
        public virtual void ReadingABlogWillShowUpInTheReadBlogsList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reading a blog will show up in the read blogs list", new string[] {
                        "blog"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reader",
                        "Blog Name"});
            table5.AddRow(new string[] {
                        "Wiljag",
                        "Dit is mijn eerste blog"});
#line 29
 testRunner.Given("The following blog read events are send", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reader",
                        "Blog Name"});
            table6.AddRow(new string[] {
                        "Wiljag",
                        "Deze blog heeft informatie over Test Automation"});
#line 32
 testRunner.When("The following blog read events are send", ((string)(null)), table6, "When ");
#line 35
 testRunner.And("\'Wiljag\' requests his reads", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table7.AddRow(new string[] {
                        "Dit is mijn eerste blog"});
            table7.AddRow(new string[] {
                        "Deze blog heeft informatie over Test Automation"});
#line 36
 testRunner.Then("The following blogs are returned", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
